### ISSUE TITLE
Warnings: The 'tar_options' argument has been deprecated, please use 'options' instead.

### ISSUE THREAD

**Issue by GabLeRoux** [saltstack-formulas/sun-java-formula#23]
Minor issue

> Warnings:
> The 'tar_options' argument has been deprecated, please use 'options' instead.  Name: /usr/share/java - Function: archive.extracted - Result: Changed Started: - 15:56:33.864308 Duration: 8590.195 ms

Just to let you know this, it will need to be updated one day ;)
https://github.com/saltstack-formulas/sun-java-formula/blob/master/sun-java/init.sls#L32

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.archive.html#salt.states.archive.extracted
> New in version 2016.11.0: The tar_options and zip_options parameters have been deprecated in favor of a single argument name.

**Comment by aboe76** [comment]
@GabLeRoux could you provide a pull request?

**Comment by soniah** [comment]
I've added a PR. Took 2 minutes. The _power of hub_

**Comment by aboe76** [comment]
merged https://github.com/saltstack-formulas/sun-java-formula/pull/24

**Comment by GabLeRoux** [comment]
Thanks, I should have sent a pr, hub is so awesome indeed, but I wasn't setup to run this quickly. Glad it got fixed! :champagne:

**Comment by soniah** [comment]
Hi @GabLeRoux sorry it was bit of a snarky comment :-0

I run several projects and getting people to submit PR's is like pulling teeth, I always like to _encourage_ it :-)
