### ISSUE TITLE
Fedora 25/26 Packaging owns /usr/lib/java/

### ISSUE THREAD

**Issue by noelmcloughlin** [saltstack-formulas/sun-java-formula#33]
In Fedora 26 this formula installation is broken - to be investigated.

Analysis from @vutny 

This is a Fedora supplied package which just creates empty directories, nothing else: javapackages-tools  ... This package provides macros and scripts to support Java packaging. I assume this has nothing to do with OpenJDK upstream distribution. And dnf upgrades will work just fine.  I think the best approach would be to try to remove /usr/lib/java empty directory. If it exists and not empty, further states should fail, because there's something very custom on a target system.In such case we have corresponding configuration options available to be set by user explicitly in Pillar or Grains.

-- also noting ---In Fedora 26 the package apache-commons-daemon  drops two files into /usr/lib/java/ as part of default workstation installation so handling via salt becomes tricky.  

The preferred behaviour is a default formula working by default on main distros without pre-config.

**Comment by noelmcloughlin** [comment]
Also noting both sqlplus and sqldeveloper salt formulas set prefix to /usr/lib/oracle/ as default.

**Comment by sroegner** [comment]
The formula was conceived to help on older platforms that didn't have any reasonable native way of installing java. Trying to make it work "right" on newer distributions that have multiple java installation paths built-in we'd have to decide whether to incorporate the native stack(s) or work around and aside them.

The former approach probably means an implementation per distribution with a potentially large number of dependencies pulled by those packages - the latter will not work as soon as you install other tools that either directly depend on or implicitly expect the native installation.
@noelmcloughlin I see you doing a lot of tool-related work - I personally am more interested in server environments - do you maybe have a solution already in mind that would work for you?

**Comment by noelmcloughlin** [comment]
Enterprise Linux default installation typically will exclude JDK so options are less muddy, but as desktop linux default installation likely include JDK we must assume /usr/lib/java/ symlink cannot work going forward - unless someone has nice solution.

The Oracle documentation is unhelpful, but the official jdk-8u131-linux-x64.RPM does install to /usr/java/ so this location, being unofficially owned by Oracle, seems best candidate.  Otherwise /usr/lib/oracle/java/ should work for everyone - and alternatives system makes this transparent.

**Comment by noelmcloughlin** [comment]
`[ERROR   ] Directory exists where the symlink /usr/lib/java should be`

**Comment by noelmcloughlin** [comment]
known workaround:  
$ sudo rpm -e javapackages-tools --nodeps
$ <run formula>
$ sudo yum install -y javapackages-tools

**Comment by noelmcloughlin** [comment]
Hi @vutny, do you have any ideas regarding best workaround?  Like following?

`+  {%- if salt['grains.get']('os_family') == 'RedHat' %}
+## Workaround for someone else owning /usr/lib/java ##
+sun-java-usr-lib-backup:
+  cmd.run: mv {{ java.java_home }} {{ java.java_home }}_java_backup 2>/dev/null || echo ok
+    - require_in:
+      - file: update-javahome-symlink
+  {% endif %}
+
 update-javahome-symlink:
   file.symlink:
     - name: {{ java.java_home }}
     - require:
       - archive: unpack-jdk-archive
 
+  {%- if salt['grains.get']('os_family') == 'RedHat' %}
+sun-java-usr-lib-restore:
+  cmd.run: mv {{ java.java_home }}_java_backup/* {{ java.java_home }} 2>/dev/null || echo ok
+    - require:
+      - cmd: sun-java-usr-lib-backup
+  file.absent:
+    - name: {{ java.java_home }}_java_backup
+  {% endif %}
+`

**Comment by noelmcloughlin** [comment]
Guys the Issue is open few weeks now https://github.com/saltstack-formulas/sun-java-formula/issues/33 and analysed by two community members.
