### ISSUE TITLE
Downloading Java Fails

### ISSUE THREAD

**Issue by bradenwright** [saltstack-formulas/sun-java-formula#36]
I'm on Ubuntu 16.04 and when this formula runs does not download the full file, but it does exit 0

https://github.com/saltstack-formulas/sun-java-formula/blob/master/sun-java/init.sls#L27

eg `curl -L -s -o '/usr/share/java/jdk-8u144-linux-x64.tar.gz' 'http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz'`

This causes the untar/gzip to fail.  I was able to successfully download the file via:

`wget --no-cookies --no-check-certificate --header "Cookie: oraclelicense=a" http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz
--2017-08-03 22:41:59--  http://download.oracle.com/otn-pub/java/jdk/8u144-b01/090f390dda5b47b9b721c7dfaa008135/jdk-8u144-linux-x64.tar.gz`

Does anyone know a curl command that will work (ie accept the license)?  Figured that would be a simpler tweak, but if not I can refactor to use wget

**Comment by noelmcloughlin** [comment]
The settings.sls has the following.

`{%- set default_dl_opts      = '-b oraclelicense=accept-securebackup-cookie -L -s' %}`

**Comment by noelmcloughlin** [comment]
@bradenwright Can you do PR to updated pillar.example?

**Comment by bradenwright** [comment]
NP.  I can get that done this weekend

**Comment by noelmcloughlin** [comment]
@bradenwright can you review https://github.com/saltstack-formulas/sun-java-formula/pull/39 please.
