### ISSUE TITLE
alternatives states fail on javac when installing JRE

### ISSUE THREAD

**Issue by aphor** [saltstack-formulas/sun-java-formula#37]
If pillars specify installing a JRE instead of a JDK, there will not be "javac" commands, by choice.

Trying to install alternatives for javac should be conditional if installing a JDK.

`
----------
          ID: javac-alt-install
    Function: alternatives.install
        Name: javac
      Result: False
     Comment: Alternative for javac not installed: update-alternatives: error: alternative path /usr/share/java/jre1.8.0_144/bin/javac doesn't exist
     Started: 05:48:29.597607
    Duration: 6.378 ms
     Changes:   
----------
          ID: javac-alt-set
    Function: alternatives.set
        Name: javac
      Result: False
     Comment: One or more requisite failed: sun-java.env.javac-alt-install
     Changes:   
`

**Comment by noelmcloughlin** [comment]
What is the correct jinja2 syntax to check if file exists?  

> {% if salt['file.exists' ]( java.javac_realcmd ) %}

> {%endif %}

**Comment by aphor** [comment]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.file_exists
`{% if salt['file.file_exists']('/the/file/to/check/fqpn') %}
Conditional stuff
{% endif %}`

**Comment by vutny** [comment]
File check in Jinja is very unreliable solution and you should avoid using that.
Because even if a file is absent during SLS compilation time, it may appear after some state run in a highstate. Salt will not see such change and not re-apply template code once again, so you will end up with wrong execution.

It's better to use `onlyif`/`unless` requisites.

**Comment by noelmcloughlin** [comment]
Thanks @vutny @aphor,  

I'll do a PR to include "onlyif / unless" check on javac-alt-install and  javac-alt-set states
