### ISSUE TITLE
java.sh sets java bin before path and breaks apt

### ISSUE THREAD

**Issue by mgomersbach** [saltstack-formulas/sun-java-formula#43]
Due to Java having a "apt" binary and the "java.sh" has the following:

export PATH=$JAVA_HOME/bin:$PATH

Reversing the order fixes the problem.

**Comment by myoung34** [comment]
Can you post the snippet from the file in question? Theres some context missing here that might get lost with someone trying to rediscover what you mention

**Comment by blbradley** [comment]
@mgomersbach Thanks for the report!

We need more information to reproduce your issue.

**Comment by noelmcloughlin** [comment]
Must be this file https://github.com/saltstack-formulas/sun-java-formula/blob/master/sun-java/java.sh

**Comment by mgomersbach** [comment]
Yes, sorry guys! It IS https://github.com/saltstack-formulas/sun-java-formula/blob/master/sun-java/java.sh
With the old order the "apt" binary from java has precedence on the debian-derivate "apt" binary.
(or actually any binary from sun would be first in the old order which could break more stuff)

**Comment by blbradley** [comment]
>  the "apt" binary from java

I'm not sure what you're talking about. Can you point us to some documentation about this?

**Comment by mgomersbach** [comment]
$JAVA_HOME/bin/apt

**Comment by blbradley** [comment]
I don't have an `apt` executable in either the JRE or JDK bin folder. Version: Java 8 131 b11.

**Comment by mgomersbach** [comment]
It's in the java 7 tarball

**Comment by mgomersbach** [comment]
http://docs.oracle.com/javase/7/docs/technotes/guides/apt/

**Comment by blbradley** [comment]
This formula hasn't defaulted to Java 7 in a few years. You may find an older version of the formula that works better for you.

**Comment by blbradley** [comment]
Looks like the `sun-java.env` state used to be (optional) way to manage `java.sh`, the 'profile'.

**Comment by mgomersbach** [comment]
It works perfectly with java 7.
Are you telling me that you are pointing me to a different repo because you don't understand that you shouldn't put the java binaries in front of original path? Regardless of it being java 7?

**Comment by blbradley** [comment]
I pointed you to a different commit in this repo's history. Not a different repo. See [this](https://github.com/saltstack-formulas/sun-java-formula/tree/0c3137c419cda288cfdf2573a4e5a3a125728b48) for old way to enable/disable the profile.

@sroegner Can you chime when you have time? Looking for your original intent and to see if this potential change would break anything on your end.

**Comment by mgomersbach** [comment]
Ah thank you, yes regardless of my issue it would still be better to reverse the order. I should have phrased it that way.

**Comment by sroegner** [comment]
I agree that the PATH setting in the profile is not optimal - it was originally put in place to easily provide Java to all users on older RedHat systems while avoiding the alternatives system. All the code dealing with alternatives was added much later and is somewhat redundant - you now have the _java_ binary in the PATH twice. Best way IMO to deal with this might be to refactor the alternatives code into its own state and keep that new state and the env.sls both optional.

**Comment by mgomersbach** [comment]
Agreed. 
Still, either optional or not.
 The error is the order. 
Whether you have a problem now or not.
The order is PATH + OTHERPATH. So that can still be fixed. Regardless of what will be chosen in the future.

**Comment by blbradley** [comment]
> When reversed it will be ok. (and in line with how everybody else uses it)

Can you show us where you have observed other Java users using your proposed change? Google'ing has not been fruitful for me.

**Comment by mgomersbach** [comment]
First I had to show which file. (which was easy to easy as I cloned AND fixed the problem)
Then had to explain the problem as it is apparently not obvious that you should prepend but append a path.
Then I needed to show documentation.
Now I have to show, you are supposed to put added path to the end again? (after saying it several times)
Any experience in Linux or just trying to understand what happens after explaining it multiple times should have been enough.
It is a very simple concept. Add additions to end of path. Otherwise functionality of system gets overridden.
Do you really not get the explanation? Maybe I should draw it?

**Comment by blbradley** [comment]
We have 98 forks of this formula, and some users put this project's repo URL directly into their GitFS repo list. This gives us about 100 users. The complexity of this project is growing. So, the issue in not so 'simple'.

I understand the particular issue _you_ are having _after_ asking for more information about your environment. If _you_ would have given enough information to reproduce your issue upfront, we wouldn't need to ask.

_Please_ refrain from your condescending tone if you wish to continue the discussion.

It is _not_ obvious. I have at least ten years of Linux experience and have not seen a previous situation where PATH is appended instead of prepended.

**Comment by mgomersbach** [comment]
I do not want to continue the discussion.
Asking for documentation for something simple as not adding the path in front (MANY reasons. Most of them security) is more condescending than getting frustrated with the burocracy.
If you have 10 years of Linux experience and still do not get the implications of adding path in front. I would fear for your professional life.
I do not think it is the case. 
And I am really sure that if anyone took the effort to think about the implications of putting the path in front we would not be having this "discussion".

So let me get this clear. In the 10 years you have always prepended the path?
That means that all those systems you did that to, now are fairly easy compromisable as any binary with the same name in that path will override OS function.

Like I said. I do not wish to continue the discussion because the fix does not deserve all this attention.
Close it as "WONTFIX" because I will not bow to some BOFH that I use "kinder" language while being pushed around with "can I see docs".

Please use the force (Google) as you are clearly very unwilling to even think about untill I become "nice".

That's the beauty of Github. You keep the bug. I'll keep the fork.
I wish you a very nice future with prepending paths :)

**Comment by myoung34** [comment]
if youd like to submit a pr instead of an issue with very little information, please feel free to do so.
